ALTER TABLE "metrics" ALTER COLUMN "subscribe_count" SET DATA TYPE integer;
ALTER TABLE "metrics" ALTER COLUMN "subscribe_count" SET DEFAULT 0;
ALTER TABLE "metrics" ALTER COLUMN "unsubscribe_count" SET DATA TYPE integer;
ALTER TABLE "metrics" ALTER COLUMN "unsubscribe_count" SET DEFAULT 0;
ALTER TABLE "metrics" ALTER COLUMN "send_count" SET DATA TYPE integer;
ALTER TABLE "metrics" ALTER COLUMN "send_count" SET DEFAULT 0;
ALTER TABLE "metrics" ALTER COLUMN "send_error_count" SET DATA TYPE integer;
ALTER TABLE "metrics" ALTER COLUMN "send_error_count" SET DEFAULT 0;
ALTER TABLE "metrics" ALTER COLUMN "exchange_rate" SET DATA TYPE varchar;
ALTER TABLE "metrics" ALTER COLUMN "exchange_rate" DROP DEFAULT;