swagger: "2.0"
info:
  version: "1.0.0"
  title: "BTC application"
  description: |
    You need to implement an API service that will allow you to:
    1. Get the current BTC UAH rate.
    2. Subscribe emails to receive the exchange rate.
    3. Send current rate to all subscribed emails.

    Business requirements:
    - get current bitcoin (BTC) rate in hryvnia (UAH)
    - subscribe email to receive information about the change in the exchange rate
    - send current rate to all subscribed users

    Technical details:
    - service application:
        - unsubscribe email flow
        - get all emails both subscribed and unsubscribed flow with statuses
        - send metrics to prometheus flow:
            - subscribe email count
            - unsubscribe email count
            - send email count
            - send email error count
            - exchange rate gauge
        - get prometheus metrics flow
    - worker application:
        - scrape metrics by worker
        - store to metrics table

    Additional requirements:
    1. The service must comply with the API described below. Do not protect the API with an authentication layer.
    2. All data for the application must be stored in database.
    3. The repository must have a docker-compose.yml that allows you to run the system in Docker: 
        - service application
        - worker application
        - database
    4. You can also add comments or a description of the logic of the work in the README.md document. The correct logic can be an advantage when evaluating if you do not fully complete the task.

    Expected tech stack:
    - NestJS
    - TypeScript
    - PostgreSQL
    - Prisma
    - Docker
    - Prometheus

    Optional:
    - Use CQRS pattern with nestjs lib
    - Replace default logger with Pino logger and add request id to logs
    - Add unit tests
    - Add daily exchange rate email at 9:00 AM Kyiv time
    - Fetch exchange rate hourly and send email if exchange rate changed more than 5% since last email

    Docker compose components:
    - service_app
    - worker_app
    - database

    Completed task must be uploaded to GitHub (public repository) and sent back to recruiter as a link to the repository.

    You can use all available information, but do the task by yourself.
    Feel free to ask any questions.

    Good luck!
---

